export const SHOW_NOTIFICATION_EVENT = 'SHOW_NOTIFICATION_EVENT';
export const HIDE_NOTIFICATION_EVENT = 'HIDE_NOTIFICATION_EVENT';
export const HIDE_NOTIFICATION_EVENT_BY_TAG = 'HIDE_NOTIFICATION_EVENT_BY_TAG';
export const NOTIFICATIONS_UPDATED = 'NOTIFICATIONS_UPDATED';
