name: 'Helm Deploy'
runs:
  using: 'docker'
  image: 'alpine/helm:3.6.3'
  steps:
  - run: |
      export CHART_FOLDER=deployment/app-chart
      helm lint $CHART_FOLDER
  - name: helm deploy
    uses: koslib/helm-eks-action@v1.8.0
    env:
      KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
    with:
      command: |
        helm --namespace $DEPLOYMENT_NAMESPACE upgrade --install --create-namespace $APP_NAME $CHART_FOLDER \
          --set image.tag=$DOCKER_ENV_TAG \
          --set environment.near_env=${secrets.NEAR_ENV} \
          --set environment.near_contract_name=${secrets.NEAR_CONTRACT_NAME} \
          --set environment.next_public_api_url=${secrets.NEXT_PUBLIC_API_URL}
          --set environment.next_public_google_analytics_key=${secrets.NEXT_PUBLIC_GOOGLE_ANALYTICS_KEY}
          --set environment.next_public_near_env=${secrets.NEXT_PUBLIC_NEAR_ENV}
          --set ingress.host=${secrets.K8S_INGRESS_HOST}
