name: 'Helm Deploy'
runs:
  using: 'composite'
  steps:
  - name: helm deploy
    uses: koslib/helm-eks-action@v1.8.0
    env:
      KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
    with:
      command: |
        export CHART_FOLDER=deployment/app-chart
        helm lint $CHART_FOLDER
        helm --namespace $DEPLOYMENT_NAMESPACE upgrade --install --create-namespace $APP_NAME $CHART_FOLDER \
          --set image.tag=$DOCKER_ENV_TAG \
          --set environment.near_env=${NEAR_ENV} \
          --set environment.near_contract_name=${NEAR_CONTRACT_NAME} \
          --set environment.next_public_api_url=${NEXT_PUBLIC_API_URL}
          --set environment.next_public_google_analytics_key=${NEXT_PUBLIC_GOOGLE_ANALYTICS_KEY}
          --set environment.next_public_near_env=${NEXT_PUBLIC_NEAR_ENV}
          --set ingress.host=${K8S_INGRESS_HOST}
