name: 'Helm Deploy'
runs:
  using: 'composite'
  steps:
  - name: helm deploy
    uses: koslib/helm-eks-action@v1.8.0
    env:
      KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
    with:
      command: |
        export CHART_FOLDER=deployment/app-chart
        helm lint $CHART_FOLDER
        helm --namespace $DEPLOYMENT_NAMESPACE upgrade --install --create-namespace $APP_NAME $CHART_FOLDER \
          --set image.tag=$DOCKER_ENV_TAG \
          --set environment.near_env=${NEAR_ENV} \
          --set environment.near_contract_name=${NEAR_CONTRACT_NAME} \
          --set environment.roketo_contract_name=${ROKETO_CONTRACT_NAME} \
          --set environtment.roketo_multicall_name=${ROKETO_MUTLTICALL_NAME} \
          --set environment.api_url=${API_URL}
          --set environment.google_analytics_key=${GOOGLE_ANALYTICS_KEY}
          --set environment.log_rocket_app_id=${LOG_ROCKET_APP_ID}
          --set environment.near_env=${NEAR_ENV}
          --set ingress.host=${K8S_INGRESS_HOST}
