import { Token } from 'types/token';

export const tokens = {
  NEAR: {
    createdAt: '2021-12-07T19:15:52.793Z',
    transactionHash: null,
    updateTransactionHash: null,
    createTimestamp: null,
    updateTimestamp: '1639053338980000000',
    id: 'NEAR',
    ownerId: '',
    totalSupply: '',
    decimals: 24,
    icon: 'customIcon',
    name: null,
    reference: null,
    referenceHash: null,
    spec: null,
    symbol: 'NEAR',
    price: '10.68',
    balance: '5.1002',
    tokenId: '',
  },
  BIBA: {
    createdAt: '2021-12-07T19:15:52.793Z',
    transactionHash: null,
    updateTransactionHash: null,
    createTimestamp: null,
    updateTimestamp: '1639053338980000000',
    id: 'BIBA',
    ownerId: '',
    totalSupply: '',
    decimals: 24,
    icon: 'customIcon',
    name: null,
    reference: null,
    referenceHash: null,
    spec: null,
    symbol: 'BIBA',
    price: '10.68',
    balance: '5.1002',
    tokenId: '',
  },
} as unknown as Record<string, Token>;
