apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "astro-ui.fullname" . }}-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    cert-manager.io/cluster-issuer: "letsencrypt"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - {{ .Values.ingress.host }}
    secretName: {{ include "astro-ui.fullname" . }}-tls-secret
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
        - path: /
          backend:
            service:
              name: {{ include "astro-ui.fullname" . }}
              port:
                number: 80
          pathType: ImplementationSpecific
