const path = require('path');
const fs = require('fs');
const camelCase = require('camelcase');
const iconsPath = path.resolve(__dirname, '..', 'assets', 'icons');

const getCamelCaseName = name => camelCase(name.split('.')[0]);

const getExportLine = fileName =>
  `export { default as ${getCamelCaseName(fileName)} } from './${fileName}';`;

const data = fs
  .readdirSync(iconsPath)
  .filter(file => file.endsWith('svg'))
  .map(getExportLine);

data.unshift('// This file wes generated by script');
data.push('');

fs.writeFileSync(path.resolve(iconsPath, 'index.ts'), data.join('\n'), {
  encoding: 'utf-8',
});
