name: 'Docker Build Publish'
runs:
  steps:
  - name: Docker Cache
    uses: actions/cache@v2
    with:
      path: |
        docker-cache/**
      key: docker

  - name: Load Cache
    run: |
      if [[ -f "docker-cache/cache.tar" ]]; then
        docker load < docker-cache/cache.tar;
      else
        mkdir docker-cache
      fi

  - name: Docker meta
    id: meta
    uses: docker/metadata-action@v3
    with:
      images: |
        ${secrets.AWS_ECR_URL}
      tags: |
        type=raw,value=latest
        type=ref,event=branch,suffix=-latest
        type=sha

  - name: Set up Docker Buildx
    uses: docker/setup-buildx-action@v1

  - name: Configure AWS credentials
    uses: aws-actions/configure-aws-credentials@v1
    with:
      aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

  - name: Login to ECR
    uses: aws-actions/amazon-ecr-login@v1

  - name: Build And Push
    uses: docker/build-push-action@v2
    with:
      context: .
      file: Dockerfile_pipelines
      platforms: linux/amd64
      tags: ${{ steps.meta.outputs.tags }}
      push: true

  - name: Save Cache
    run: |
      docker save $(docker images -qa) > docker-cache/cache.tar;
