name: 'Build and Deploy Storybook'
runs:
  steps:
  - uses: actions/setup-node@v2
    with:
      node-version: '14.16.0'
      yarn: 'yarn'

  - run: yarn install
  - run: yarn lint
  - run: yarn typecheck
  - run: yarn build-storybook

  - name: archive artifacts
        uses: actions/upload-artifact@v2
        with:
          path: |
            .storybook-static/**

  - uses: shallwefootball/s3-upload-action@1.1.3
    with:
      aws_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
      aws_bucket: "astro-storybook"
      source_dir: 'storybook-static'
