name: Deploy
on:
  workflow_dispatch:
    inputs:
      environment:
        required: true
        description: Specify environment to run on. Valid values are test, production
      tag:
        required: true
        description: Docker tag to deploy. Valid values are "latest", "<branch>-latest", "<commit_sha>", "<environment>-<commit_sha>". Exact values can be found in "Docker Build Publish" step of "Build Deploy" job.

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  HELM_GOOGLE_ANALYTICS_KEY: ${{ secrets.GOOGLE_ANALYTICS_KEY }}
  HELM_LOG_ROCKET_APP_ID: ${{ secrets.LOG_ROCKET_APP_ID }}
  KUBE_CONFIG_DATA:  ${{ secrets.KUBE_CONFIG_DATA }}
  NODE_OPTIONS: "--max-old-space-size=7168"
  HELM_NEXT_PUBLIC_LAUNCHDARKLY_ID: ${{ secrets.NEXT_PUBLIC_LAUNCHDARKLY_ID }}
  HELM_NEXT_PUBLIC_LAUNCHDARKLY_SDK_KEY: ${{ secrets.NEXT_PUBLIC_LAUNCHDARKLY_SDK_KEY }}
  HELM_DD_APPLICATION_ID: ${{ secrets.DD_APPLICATION_ID }}
  HELM_DD_CLIENT_TOKEN: ${{ secrets.DD_CLIENT_TOKEN }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    environment:
      name: ${{ github.event.inputs.environment }}
    steps:
    - uses: actions/checkout@v3
    - name: Set Environment
      run: |
        cat ".github/env.common" >>$GITHUB_ENV
        cat ".github/env.${{ github.event.inputs.environment }}" >>$GITHUB_ENV

    - name: Helm Deploy
      uses: near-daos/github-actions/deploy@main
      with:
        name: astro-ui
        namespace: ${{ env.DEPLOYMENT_NAMESPACE }}
        tag: ${{ github.event.inputs.tag }}
        chart_directory: deployment/app-chart
